### PR TITLE
add joiner/joinerfunc and joiner tests

### PR DESCRIPTION
**Pull request by lanzafame**
I essentially copied the work already done on the `Divider` interface but changed it to `Joiner`. Not sure if this is the way you wanted to go but it seemed odd not to have it. 

Cheers for this package! It addresses a problem I have been facing for a while now, which is the naming and standardizing of string formatting functions. 👍

### CODE REVIEW

**Comment by esemplastic** [comment]
Yes, I had declare the type of `Joiner` for future use and implementation. 

LGTM. Is a good start for the `Joiner`, and I'm impressed that you fill the `Joiner` tests too with this PR!

You can continue and add more things to the `Joiner`, I usually thing ideas and implementations when *I'm facing a problem on other projects*, something is coming to me from the universe and I open the unis folder and implement the idea :)

**Review by esemplastic — APPROVED** [review]
Yes, I had declare the type of `Joiner` for future use and implementation. 

LGTM. Is a good start for the `Joiner`, and I'm impressed that you fill the `Joiner` tests too with this PR!

You can continue and add more things to the `Joiner`, I usually thing ideas and implementations when *I'm facing a problem on other projects*, something is coming to me from the universe and I open the unis folder and implement the idea :)

**Comment by esemplastic** [comment]
Just something came up now, I see that you implemented the `NewJoinerChain`. Look how I'm thinking it, the main base is the `Processors` , everything else is just `before/pre` or `after/post` action from a processor. For example the validators are before a processor, i.e;` m := unis.If(unis.NewMatcher("[0-9]+$"], unis.NewPrepender("Integer: ")); m("15")` the `m` is the result of the `if` statement, which takes a validator and a processor, the `m` is a processor. Maybe it was a good idea to implement chain on the joiners too I just can't think a usage right now, but you have your reasons, so we'll see in the future, for now it doesnt' hurts, good job :)

**Comment by esemplastic** [comment]
Just something came up now, I see that you implemented the `NewJoinerChain`. Look how I'm thinking it, the main base is the `Processors` , everything else is just `before/pre` or `after/post` action from a processor. For example the validators are before a processor, i.e;` m := unis.If(unis.NewMatcher("[0-9]+$"], unis.NewPrepender("Integer: ")); m("15")` the `m` is the result of the `if` statement, which takes a validator and a processor, the `m` is a processor. Maybe it was a good idea to implement chain on the joiners or maybe the choosen name of chain is not correct because it takes an argument of other type than Joiner. You should have your reasons to choose that name func to that job, so we'll see in the future, for now it doesnt' hurts, good job, I'm waiting more and more on that :)

**Comment by esemplastic** [comment]
Just something came up now, I see that you implemented the `NewJoinerChain`. Look how I'm thinking it, the main base is the `Processors` , everything else is just `before/pre` or `after/post` action from a processor. For example the validators are before a processor, i.e;` m := unis.If(unis.NewMatcher("[0-9]+$"], unis.NewPrepender("Integer: "), unis.ClearProcessor); m("15")` the `m` is the result of the `if` statement, which takes a validator and a processor, the `m` is a processor. Maybe it was a good idea to implement chain on the joiners or maybe the choosen name of chain is not correct because it takes an argument of other type than Joiner. You should have your reasons to choose that name func to that job, so we'll see in the future, for now it doesnt' hurts, good job, I'm waiting more and more on that :)

**Comment by esemplastic** [comment]
@lanzafame  Just something came up now, I see that you implemented the `NewJoinerChain`. Look how I'm thinking it, the main base is the `Processors` , everything else is just `before/pre` or `after/post` action from a processor. For example the validators are before a processor, i.e;` m := unis.If(unis.NewMatcher("[0-9]+$"], unis.NewPrepender("Integer: "), unis.ClearProcessor); m("15")` the `m` is the result of the `if` statement, which takes a validator and a processor, the `m` is a processor. Maybe it was a good idea to implement chain on the joiners or maybe the choosen name of chain is not correct because it takes an argument of other type than Joiner. You should have your reasons to choose that name func to that job, so we'll see in the future, for now it doesnt' hurts, good job, I'm waiting more and more on that :)

**Comment by lanzafame** [comment]
@esemplastic I am also unsure about the `NewJoinerChain` but it allows for a more clean implementation of certain things, for example: 
```go
// PathJoiner takes two strings and returns them joined by a "/"
var PathJoiner = unis.NewJoiner("/")

// XMLFile appends the xml file extension
var XMLFile = unis.NewAppender(".xml")

// PathToXMLFile provides a path with an xml file extension appended
var PathToXMLFile = unis.NewJoinerChain(PathJoiner, ToLower, XMLFile)
```
This obviously isn't the most generic path joining method but for what I need it works well. Hopefully the example helps show the reasoning behind the `NewJoinerChain`.

**Comment by esemplastic** [comment]
Thanks for answering back with a code-snippet @lanzafame,
This subject is very important so I took the initiative to open a new [issue](https://github.com/esemplastic/unis/issues/4) for discussion (it will be easier for new or existing users to participate too)

**Pull request merged**
